services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: referral_system_db
    ports:
      - 5435:5432

  redis:
    image: redis:latest
    restart: always
    container_name: referral_system_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'make start'
    env_file:
      - .env
    environment:
      IN_DOCKER: 'True'
    container_name: referral_system_web
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    profiles:
      - full


volumes:
  postgres_volume:
  redis_volume:
    driver: local
